INSERT INTO `m_companies` (`id`, `company`, `sort`, `deleted_at`, `created_at`, `updated_at`) VALUES
                                                                                                  (NULL, '丸井グループ', '10', NULL, NULL, NULL),
                                                                                                  (NULL, '丸井', '20', NULL, NULL, NULL),
                                                                                                  (NULL, 'エポスカード', '30', NULL, NULL, NULL),
                                                                                                  (NULL, 'MRI債権回収', '40', NULL, NULL, NULL),
                                                                                                  (NULL, 'エポス少額短期保険', '50', NULL, NULL, NULL),
                                                                                                  (NULL, 'エイムクリエイツ', '60', NULL, NULL, NULL),
                                                                                                  (NULL, 'エムアンドシーシステム', '70', NULL, NULL, NULL),
                                                                                                  (NULL, 'マルイファシリティーズ', '80', NULL, NULL, NULL),
                                                                                                  (NULL, 'ムービング', '90', NULL, NULL, NULL),
                                                                                                  (NULL, 'マルイホームサービス', '100', NULL, NULL, NULL),
                                                                                                  (NULL, 'マルイキットセンター', '110', NULL, NULL, NULL),
                                                                                                  (NULL, 'tsumiki証券', '120', NULL, NULL, NULL),
                                                                                                  (NULL, 'D2C&Co.', '130', NULL, NULL, NULL),
                                                                                                  (NULL, 'okos', '140', NULL, NULL, NULL),
                                                                                                  (NULL, '丸井健康保険組合', '150', NULL, NULL, NULL),
                                                                                                  (NULL, 'マルイグループユニオン・福祉会', '160', NULL, NULL, NULL);
